name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'  # Ensure this matches the version you need

      - name: Install Go dependencies
        run: |
          go mod tidy
          go get github.com/gorilla/mux

      - name: Build application
        run: |
          go build -o go-app

      - name: Archive files
        run: |
          zip go-app.zip go-app
          tar -czvf go-app.tar.gz go-app

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            go-app.zip
            go-app.tar.gz

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t navaneetha084/go-app:latest .
          docker push navaneetha084/go-app:latest
