name: Trivy Security Scan

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.34.0_Linux-64bit.deb

      - name: Scan Docker Image for Vulnerabilities
        run: |
          trivy image --format table devopshub2021/go-app:latest

      - name: Scan Repository for Vulnerabilities
        run: |
          trivy repo --format table https://github.com/devopshubin/go-app.git
